### ISSUE TITLE
Can't run PyCNC - [Errno 2] No such file or directory: '/dev/i2c-1'

### ISSUE THREAD

**Issue by iSQL** [Nikolay-Kha/PyCNC#23]
> pi@raspberrypi:~/Downloads/pycnc $ sudo  ./pycnc
Traceback (most recent call last):
  File "./pycnc", line 3, in <module>
    import cnc.main
  File "/home/pi/Downloads/pycnc/cnc/main.py", line 10, in <module>
    from cnc.gmachine import GMachine, GMachineException
  File "/home/pi/Downloads/pycnc/cnc/gmachine.py", line 4, in <module>
    from cnc import hal
  File "/home/pi/Downloads/pycnc/cnc/hal.py", line 101, in <module>
    from cnc.hal_raspberry.hal import *
  File "/home/pi/Downloads/pycnc/cnc/hal_raspberry/hal.py", line 6, in <module>
    from cnc.sensors import thermistor
  File "/home/pi/Downloads/pycnc/cnc/sensors/thermistor.py", line 34, in <module>
    import ads111x as adc
  File "/home/pi/Downloads/pycnc/cnc/sensors/ads111x.py", line 35, in <module>
    i2c = __I2CDev()
  File "/home/pi/Downloads/pycnc/cnc/sensors/ads111x.py", line 16, in __init__
    self._dev = os.open("/dev/i2c-1", os.O_SYNC | os.O_RDWR)
OSError: [Errno 2] No such file or directory: '/dev/i2c-1'

This is what I get. Is my RPi device bad or did I messed up something?

**Comment by Nikolay-Kha** [comment]
Hello. Please enable I2C interface for your Raspberry Pi with 'raspi-config' util(https://www.raspberrypi.org/documentation/configuration/raspi-config.md)
