### ISSUE TITLE
Can't start with pypy

### ISSUE THREAD

**Issue by spaxxomatic** [Nikolay-Kha/PyCNC#48]
Hi Nikolay
PyCNC works fine with Python, but I can't get it running with pypy
Could you mabe give me a hint? Thanks !

> pypy ./pycnc
---- ads111x is not detected ----
Traceback (most recent call last):
  File "./pycnc", line 3, in <module>
    import cnc.main
  File "/root/PyCNC/cnc/main.py", line 10, in <module>
    from cnc.gmachine import GMachine, GMachineException
  File "/root/PyCNC/cnc/gmachine.py", line 4, in <module>
    from cnc import hal
  File "/root/PyCNC/cnc/hal.py", line 101, in <module>
    from cnc.hal_raspberry.hal import *
  File "/root/PyCNC/cnc/hal_raspberry/hal.py", line 12, in <module>
    pwm = rpgpio.DMAPWM()
  File "/root/PyCNC/cnc/hal_raspberry/rpgpio.py", line 290, in __init__
    self._phys_memory.get_bus_address())
  File "/root/PyCNC/cnc/hal_raspberry/rpgpio_private.py", line 140, in write_int
    ctypes.c_uint32.from_buffer(self._memmap, address).value = int_value
  File "/usr/lib/pypy/lib_pypy/_ctypes/basics.py", line 95, in from_buffer
    result._ensure_objects()['ffffffff'] = obj
TypeError: 'NoneType' object does not support item assignment

**Comment by spaxxomatic** [comment]
Sorry, just noticed that my post is a duplicate of https://github.com/Nikolay-Kha/PyCNC/issues/20
